name: Check build

on:
  pull_request:
    types:
    - opened
    - synchronize
    - reopened

permissions:
  contents: read

jobs:
  build-test:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: read

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@6c439dc8bdf85cadbbce9ed30d1c7b959517bc49 # v2.12.2
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set Up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          cache: 'pip'
          cache-dependency-path: './docs/requirements.txt'
          python-version: '3.12.10'

      - name: Install Dependencies
        shell: bash
        run: pip install -r requirements.txt
       
      - name: Build
        shell: python
        run: |
          import os
          import subprocess

          def build_wheel():
              if not os.path.exists('dist'):
                  os.makedirs('dist')
              subprocess.check_call([ 'python', '-m', 'build', '--wheel' ])

          build_wheel()

