name: semantic release

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}

permissions:
  contents: read

jobs:
  release:
    if: ${{ !startsWith(github.event.head_commit.message, 'chore(release):') }}
    runs-on: ubuntu-latest

    permissions:
      contents: write
      actions: write
      id-token: write

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0
          persist-credentials: false

      - name: Reset branch
        run: |
          git reset --hard ${{ github.sha }}

      - name: Setup Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.12.10'
          cache: 'pip'

      - name: Install dependencies
        shell: bash
        run: pip install -r requirements.txt
        
      - name: Release
        run: |
          # symbolic link to fix an error when running a build_command
          sudo ln -s /home/runner/_work/_tool/Python/3.12.10/x64/lib/libpython3.12.so.1.0 /usr/lib/libpython3.12.so.1.0
          semantic-release version
          semantic-release publish

      - name: Store the distribution packages
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2
        with:
          name: python-package-distributions
          path: dist/
          retention-days: 2


  publish-to-pypi:
    needs: release
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/intel-sphinx-theme
    permissions:
      id-token: write # IMPORTANT: mandatory for trusted publishing
    
    steps:
      - name: Download the wheel
        id: download-artifacts
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 #v4.3.0
        with:
          name: python-package-distributions
          path: dist/
        continue-on-error: true

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc # v1.12.4
        if: steps.download-artifacts.outcome == 'success'
        with:
          packages-dir: dist
          print-hash: true
          verbose: true


